Repository fedewf1/repositorio-tp2, pull requests merged in 2023-06, with the labels that each got.

#52 Issues 1 tp 5
  TP2_Grupo45/pom.xml
  TP2_Grupo45/src/main/resources/templates/index.html
Labels: documentation, Diseño

#56 Agregando dependencias @component y Atowired
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/HomeController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaArticulos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Articulo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Producto.java
  TP2_Grupo45/src/main/resources/templates/articulos_index.html
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/layouts/footer.html
  TP2_Grupo45/src/main/resources/templates/layouts/nav.html
  TP2_Grupo45/src/main/resources/templates/nuevo_articulo.html
  TP2_Grupo45/src/main/resources/templates/nuevo_producto.html
  TP2_Grupo45/src/main/resources/templates/productos.html
Labels: documentation, Diseño

#64 Issue 1 tp6 paquete service e imp
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
Labels: Diseño

#65 Se agrega y/o modifica: ConsejoController,HTMLs para Consejos,estilos
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Consejo.java
  TP2_Grupo45/src/main/resources/static/css/estilos.css
  TP2_Grupo45/src/main/resources/templates/consejos.html
  TP2_Grupo45/src/main/resources/templates/consejos_de_salud.html
  TP2_Grupo45/src/main/resources/templates/detalle_consejo.html
  TP2_Grupo45/src/main/resources/templates/layouts/footer.html
  TP2_Grupo45/src/main/resources/templates/layouts/nav.html
  TP2_Grupo45/src/main/resources/templates/nuevo_consejo.html
Labels: documentation, Diseño

#58 Se modifican los archivos de sucursales.html, contacto.html considerando
  TP2_Grupo45/pom.xml
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Sucursal.java
  TP2_Grupo45/src/main/resources/templates/contacto.html
  TP2_Grupo45/src/main/resources/templates/layouts/header.html
  TP2_Grupo45/src/main/resources/templates/sucursales.html
Labels: documentation, Diseño

#66 Se agrega y/o modifica ServicioController,HTMLs,estilos
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Servicio.java
  TP2_Grupo45/src/main/resources/static/css/estilos.css
  TP2_Grupo45/src/main/resources/templates/nuevo_servicio.html
  TP2_Grupo45/src/main/resources/templates/servicio_de_paseos.html
  TP2_Grupo45/src/main/resources/templates/servicios.html
Labels: documentation, Diseño

#69 Delete TP2_Grupo45/bin directory
  TP2_Grupo45/bin/.gitignore
  TP2_Grupo45/bin/.mvn/wrapper/maven-wrapper.jar
  TP2_Grupo45/bin/.mvn/wrapper/maven-wrapper.properties
  TP2_Grupo45/bin/mvnw
  TP2_Grupo45/bin/mvnw.cmd
  TP2_Grupo45/bin/pom.xml
  TP2_Grupo45/bin/src/main/resources/application.properties
  TP2_Grupo45/bin/src/main/resources/static/css/estilos.css
  TP2_Grupo45/bin/src/main/resources/static/images/Buzo_para_perros.jpg
  TP2_Grupo45/bin/src/main/resources/static/images/gaiola_hamster.jpg
  TP2_Grupo45/bin/src/main/resources/static/images/mochila_pokemon.jpg
  TP2_Grupo45/bin/src/main/resources/static/images/moises_mascota.jpeg
  TP2_Grupo45/bin/src/main/resources/static/images/petstore.jpg
  TP2_Grupo45/bin/src/main/resources/static/images/set_paseo_pitbull.jpg
  TP2_Grupo45/bin/src/main/resources/static/images/whiskas.jpg
  TP2_Grupo45/bin/src/main/resources/templates/consejos_de_salud.html
  TP2_Grupo45/bin/src/main/resources/templates/contacto.html
  TP2_Grupo45/bin/src/main/resources/templates/index.html
  TP2_Grupo45/bin/src/main/resources/templates/layouts/footer.html
  TP2_Grupo45/bin/src/main/resources/templates/layouts/header.html
  TP2_Grupo45/bin/src/main/resources/templates/layouts/nav.html
  TP2_Grupo45/bin/src/main/resources/templates/nuevo_producto.html
  TP2_Grupo45/bin/src/main/resources/templates/productos.html
  TP2_Grupo45/bin/src/main/resources/templates/servicio_de_paseos.html
  TP2_Grupo45/bin/src/main/resources/templates/sucursales.html
Labels: bug

#71 Issue 5 version 1 tp6
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
Labels: bug

#73 Tp6 issue4 capa service servicios
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
  TP2_Grupo45/src/main/resources/static/images/fbooklogo.svg
  TP2_Grupo45/src/main/resources/static/images/instagramlogov2.png
  TP2_Grupo45/src/main/resources/static/images/maillogo.svg
  TP2_Grupo45/src/main/resources/static/images/twitterlogo.svg
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/nuevo_consejo.html
  TP2_Grupo45/src/main/resources/templates/nuevo_servicio.html
Labels: bug, documentation, Diseño

#74 Tp6 modificaciones extras
  TP2_Grupo45/src/main/resources/static/css/estilos.css
  TP2_Grupo45/src/main/resources/static/images/fbooklogo.svg
  TP2_Grupo45/src/main/resources/static/images/instagramlogov2.png
  TP2_Grupo45/src/main/resources/static/images/maillogo.svg
  TP2_Grupo45/src/main/resources/static/images/twitterlogo.svg
  TP2_Grupo45/src/main/resources/templates/productos.html
Labels: bug, Diseño

#75 Issue2 tp6 crear productoimp e interfazproducto e impletar metodos
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
Labels: documentation, Diseño

#77 1 En el paquete service, se crean las interfacez necesarias para
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
Labels: bug, documentation, Diseño

#78 Issue 6 tp6 creacion capa servicio e imp de homecontroller
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/HomeController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaArticulos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Articulo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IHomeService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceImp.java
  TP2_Grupo45/src/main/resources/static/css/estilos.css
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/nuevo_articulo.html
Labels: documentation, Diseño

#80 Issue 7 tp6 Se creo una layout con la etiqueta aside
  TP2_Grupo45/src/main/resources/templates/consejos.html
  TP2_Grupo45/src/main/resources/templates/contacto.html
  TP2_Grupo45/src/main/resources/templates/detalle_consejo.html
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/layouts/aside.html
  TP2_Grupo45/src/main/resources/templates/nuevo_articulo.html
  TP2_Grupo45/src/main/resources/templates/nuevo_producto.html
  TP2_Grupo45/src/main/resources/templates/nuevo_servicio.html
  TP2_Grupo45/src/main/resources/templates/servicios.html
Labels: documentation, Diseño

#82 Issue 8 tp 6 arreglar errores de sucursalcontroller
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo45/src/main/resources/templates/nueva_sucursal.html
  TP2_Grupo45/src/main/resources/templates/sucursales.html
Labels: bug, documentation, Diseño

#84 Integración CommonService en Sucursal
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaProvincia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ICommonService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/CommonServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo45/src/main/resources/templates/nueva_sucursal.html
  TP2_Grupo45/src/main/resources/templates/sucursales.html
Labels: documentation, Diseño

#85 Integracion CommonService ListaProvincia en Contacto
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ContactoController.java
  TP2_Grupo45/src/main/resources/templates/contacto.html
Labels: bug, documentation, Diseño

#90 Issue 1 TP7 Grupo45 modifica pom model app properti - crea paquete repository
  TP2_Grupo45/pom.xml
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/HomeController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Articulo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Consejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Noticia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Producto.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Servicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaArticulos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/model/Noticia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IAlumnoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IHomeService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo45/src/main/resources/application.properties
Labels: documentation, Diseño

#93 Tp7 issue3 capa repository servicios
  TP2_Grupo45/pom.xml
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/EmpleadoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ServicioController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Consejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Empleado.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Servicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaConsejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IEmpleadoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IServicioRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ICommonService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IEmpleadoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/CommonServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/EmpleadoServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ListaProvincia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceMysqlImp.java
  TP2_Grupo45/src/main/resources/application.properties
  TP2_Grupo45/src/main/resources/import.sql
  TP2_Grupo45/src/main/resources/templates/contacto.html
  TP2_Grupo45/src/main/resources/templates/empleados.html
  TP2_Grupo45/src/main/resources/templates/layouts/nav.html
  TP2_Grupo45/src/main/resources/templates/nuevo_empleado.html
  TP2_Grupo45/src/main/resources/templates/nuevo_servicio.html
  TP2_Grupo45/src/main/resources/templates/servicios.html
Labels: bug, documentation, Diseño

#94 Issue 2 TP7 mapeo de producto y capa
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Categoria.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Producto.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IAlumnoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  TP2_Grupo45/src/main/resources/application.properties
  TP2_Grupo45/src/main/resources/templates/nuevo_producto.html
  TP2_Grupo45/src/main/resources/templates/productos.html
  TP2_Grupo45/src/test/java/ar/edu/unju/fi/Tp2Grupo45ApplicationTests.java
Labels: bug, documentation, Diseño

#96 Issue 2 Tp7 grupo 45
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Categoria.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Producto.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceImp.java
  TP2_Grupo45/src/main/resources/application.properties
  TP2_Grupo45/src/main/resources/templates/productos.html
Labels: bug

#98 Tp7 modificaciones extras
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/EmpleadoServiceMysqlImp.java
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/layouts/aside.html
  TP2_Grupo45/src/main/resources/templates/layouts/nav.html
Labels: Diseño

#97 1 Se Realiza el mapeo utilizando anotaciones pertenecientes al paquete
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
Labels: documentation, Diseño

#100 Issue 2 Tp7 Grupo 45
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/HomeController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Articulo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Categoria.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Producto.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaArticulos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IHomeRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ICategoriaService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IHomeService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  TP2_Grupo45/src/main/resources/templates/index.html
  TP2_Grupo45/src/main/resources/templates/nuevo_articulo.html
  TP2_Grupo45/src/main/resources/templates/productos.html
Labels: bug

#101 Tp7 issue5 nav gestion
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/EmpleadoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/GestionController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Sucursal.java
  TP2_Grupo45/src/main/resources/templates/gestion.html
  TP2_Grupo45/src/main/resources/templates/layouts/nav.html
  TP2_Grupo45/src/main/resources/templates/nueva_sucursal.html
Labels: bug, documentation, Diseño

#102 mas correcciones multiples
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ConsejoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/EmpleadoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/GestionController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/HomeController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/ProductoController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/controller/SucursalController.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entify/Noticia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Articulo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Categoria.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Consejo.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Empleado.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Noticia.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Producto.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Servicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/entity/Sucursal.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaArticulos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaProductos.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaServicio.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/listas/ListaSucursales.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IAlumnoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IConsejoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IEmpleadoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IHomeRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IProductoRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/IServicioRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/repository/ISucursalRepository.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ICategoriaService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IConsejoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IEmpleadoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IHomeService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IProductoService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/IServicioService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/ISucursalService.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ConsejoServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/EmpleadoServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/HomeServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ProductoServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/ServicioServiceMysqlImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceImp.java
  TP2_Grupo45/src/main/java/ar/edu/unju/fi/service/imp/SucursalServiceMysqlImp.java
  TP2_Grupo45/src/main/resources/templates/index.html
Labels: bug, Diseño
